/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf
Author: Ryztiq (https://sketchfab.com/Ryztiq)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wall-trim-55d5df00ae5d47099ad3853f59757596
Title: Wall Trim
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0.13, 0, -0.13]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.13, 0.08, 0]} rotation={[0, 0, -Math.PI / 2]} scale={12.56}>
            <mesh geometry={nodes.pPlane1_lambert1_0.geometry} material={materials.lambert1} position={[-2.06, -0.04, 0]} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
